### ISSUE TITLE
Closing the window tramples diagnostic report generation

### ISSUE THREAD

**Issue by TYoung86** [admiralnelson/bannerlord-error-detector#2]
Since you've wired up the exception window to kill the application;

```html
<button class='button' onclick='window.external.CloseProgram()'>
```

```
    Public Sub CloseProgram()
        Dim pid = Process.GetCurrentProcess().Id
        Dim proc As Process = Process.GetProcessById(pid)
        proc.Kill()
    End Sub
```

Further exception handlers don't get a chance to run.

Also, if somehow the exception is non-fatal, you kill the program anyway.

Could you consider _not killing the program?_

It'd let me at least get diagnostic reports generated when people crash while using Community Patch.

I got some guy recommending your modification together with the Community Patch, and it's _quite annoying to get complaints that no diagnostic report was generated during a crash._

**Comment by admiralnelson** [comment]
I am sorry for late reply,
Yeah I should put functionality to continue to program, instead of killing it.

Thanks for opening an issue, I’ll look into it and make an adjustment.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by admiralnelson** [comment]
In revision nr. 387293ce47a08aba3d791f019a36009f7770f88d
I have added option to continue the program and notice the user about this. 
It seems like we can close this issue now.
I really appreciate your report.

**Comment by YANG10-M** [comment]
t TaleWorlds.CampaignSystem.Campaign.InitializeCampaignObjectsOnAfterLoad()
   at TaleWorlds.CampaignSystem.Campaign.OnInitialize()
   at TaleWorlds.CampaignSystem.Campaign.DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, GameTypeLoadingStates& nextState)
   at StoryMode.CampaignStoryMode.DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, GameTypeLoadingStates& nextState)
   at TaleWorlds.Core.GameType.DoLoadingForGameType()
   at SandBox.CampaignGameManager.DoLoadingForGameManager(GameManagerLoadingSteps gameManagerLoadingStep, GameManagerLoadingSteps& nextStep)
   at TaleWorlds.Core.GameManagerBase.DoLoadingForGameManager()
   at TaleWorlds.MountAndBlade.GameLoadingState.OnTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch7(Module this, Single dt)

**Comment by admiralnelson** [comment]
Sorry, but this is not the place to report error/crashes related to 3rd party mods.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
